name: another workflow
on:
  workflow_call:
    inputs:
      issue_number:
        required: true
        type: string
        description: 'The issue number to post a comment on'
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
        - run: echo "smoke on the pull request ${{ inputs.issue_number }}"
  post-comment:
    needs: do-something
    runs-on: ubuntu-latest
    steps:
      - name: Post comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ inputs.issue_number }}
          body: |
            The workflow has completed successfully.
