name: Mention Harvester

on:
  issue_comment:
    types: [created]

jobs:
  mention-harvester:
    if: startsWith(github.event.comment.body, '/harvester smoke') && github.event.comment.author_association == 'COLLABORATOR'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger another workflow
        uses: actions/github-script@v4
        with:
          script: |
            const octokit = github.getOctokit(core.getInput('token'));
            const response = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'another-workflow.yml',
              ref: context.payload.pull_request.head.ref
            });
        env:
          token: ${{ secrets.GITHUB_TOKEN }}